language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "nightly"
  - pypy
matrix:
  allow_failures:
    - python: 3.4
    - python: "nightly"
    - python: pypy
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - build-essential
install:
  - "pip install -U pip setuptools wheel"
  - "pip install pytest pytest-cov python-coveralls"
  - "travis_wait pip install numpy scipy"
  - "pip install -e ."
script: py.test tests --cov skboost --cov-report term-missing
after_success:
  - coveralls
